[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/privacy"
  to = "/#/privacy"
  status = 301
  force = false
  query = {path = ":path"}

  from = "/terms"
  to = "/#/terms"
  status = 301
  force = false
  query = {path = ":path"}